version: '3.8'

services:
  db:
    image: postgres:15
    container_name: banco_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_banco
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_banco_central
    restart: always
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: api_banco
      DB_HOST: db
    ports:
      - "3000:3000"
    
    command: sh -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm run dev"

volumes:
  pgdata:
